### ISSUE TITLE
Declarative approach and Sessions. Will be possible to use them?

### ISSUE THREAD

**Issue by xando** [alex/alchimia#13]
Hi, great work!

I'm kind of new to both SQLAlchemy and Twisted, but to what I got used to is called Declarative 
http://docs.sqlalchemy.org/en/rel_0_9/orm/extensions/declarative.html and as far I know the way to manage this is by using Sessions. 

Working with them gives me 

```
'TwistedEngine' object has no attribute 'contextual_connect'
```

**Comment by glyph** [comment]
Hi @xando .

I realize that I'm pretty late to respond to this, but: no, alchimia won't support ORM features, and Sessions are an ORM feature.  The ORM in sqlalchemy has a hard dependency in many places on blocking SQL execution.

Alchimia will remain restricted to sqlalchemy core.
