### ISSUE TITLE
Motivation?

### ISSUE THREAD

**Issue by myusuf3** [alex/alchimia#7]
I would love to see the motivation for this project somewhere? what does it enable me to do? 

I could guess, but that's just wrong.

**Comment by glyph** [comment]
Alchimia allows you to coordinate access to database I/O from event-driven Twisted programs.  Although this uses threads internally, it hides those threads from the application.  This means it is _safe by default_ in the same way that most Twisted programs are: unless you see a `yield`, no concurrent I/O is happening.

**Comment by glyph** [comment]
Hopefully this answer is adequate!  If you have more questions about its utility, feel free to follow up.
